model.products = [
    
    // Stue
    {
        title: 'Sofa',
        price: 6999,
        stock: 1,
        category: 'Stue',
        id: 11,
        parentId: 1,
        subCategory: 'Sofa',
        img: 'TempBilder/1Stue/1Sofa/vintagesofaoker.jpeg',
        description: 'Pent brukt, men fortsatt en flott sofa. Stått lagret i bod siden 2005.',
        measures: 'Høyde: 80cm. Dybde: 50cm. Lengde: 170cm',
        color: ['Oker Gul'],
        country: 'Danmark',
        year: "1978",
    },
    {
        title: 'Spisestuestol',
        price: 1999,
        stock: 2,
        category: 'Spiserom',
        id: 22,
        parentId: 2,
        subCategory: 'Spisestuestol',
        img: 'TempBilder/2Spiserom/1stoler/habdulstol.png',
        description: 'Godt brukt stol, men fortsatt flott å se på.',
        measures: 'Høyde: 80cm. Dybde: 40cm. Lengde: 40cm',
        color: ['Brun'],
        country: 'Tyskland',
        year: "1967",
    },
    {
        title: 'Kjøkkenbord',
        price: 2499,
        stock: 2,
        category: 'Kjøkken',
        id: 31,
        parentId: 3,
        subCategory: 'Kjøkkenbord',
        img: 'TempBilder/1 Kjøkkenbord/vintagekjokkenbord.jpeg',
        description: '.',
        measures: 'Høyde: 80cm. Dybde: 50cm. Lengde: 170cm',
        color: ['Oker Gul'],
        country: 'Tyskland',
        year: "1998",
    },
    {
        title: 'Unikt barbord',
        price: 6799,
        stock: 2,
        category: 'Lesesal',
        id: 93,
        parentId: 9,
        subCategory: 'Bord',
        img: 'TempBilder/3Kjøkken/Tempkitchentable/8729f31b63ae4f033a520009b94acd6048-removebg-preview.png',
        description: 'Bardisk med plass til både flasker og glass, også med kjøleboks. Stamme i svart metall med fine kontraster til den gyldne fargen. Topplate av mangotre.',
        measures: 'Høyde 100cm. Dybde 45cm. Lengde 110cm.',
        color: ['Eik', ' Sort'],
        country: 'Sverige',
        year: '1961',
    },
    // Spiserom
    {
        title: 'Seng',
        price: 8499,
        stock: 3,
        category: 'Soverom',
        id: 41,
        parentId: 4,
        subCategory: 'Seng',
        img: 'TempBilder/4 Soverom/1 Seng/vintageseng2.jpeg',
        description: 'Flott, unik seng.',
        color: ['gold', 'gylden'],
        country: 'Canada',
        year: '1968',
    },

    // Kjøkken

    {
        title: 'Sofabord',
        price: 8888,
        stock: 2,
        category: 'Stue',
        id: 11,
        parentId: 1,
        subCategory: 'Sofabord',
        img: 'TempBilder/1Stue/2Sofabord/80svintagebord.jpeg',
        description: 'To små, enkle sofabord, i fin stand.',
        measures: 'Høyde 40cm. Dybde 50cm. Høyde 30cm. Dybde 30cm.',
        color: ['Treverk'],
        country: 'Danmark',
        year: '1971',
    },
    {
        title: 'Kommode',
        price: 2499,
        stock: 1,
        category: 'Soverom',
        id: 43,
        parentId: 4,
        subCategory: 'Kommode',
        img: 'TempBilder/1Stue/4Kommoder/kommodevin.jpeg',
        description: 'Fin kommode i god stand. Fin å ha på soverommet.',
        measures: 'Høyde 80cm. Dybde 50cm.',
        color: ['Treverk'],
        country: 'Finland',
        year: '1971',
    },
    {
        title: 'Skjenk ',
        price: 3299,
        stock: 2,
        category: 'Spiserom',
        id: 25,
        parentId: 2,
        subCategory: 'Skjenk',
        img: 'TempBilder/1Stue/4Kommoder/retroskjenk.jpeg',
        description: 'Godt brukt, men i god stand. Passer fint i spiserommet.',
        measures: 'Høyde 85cm. Dybde 45cm. Bredde 100cm',
        color: ['Treverk'],
        country: 'Danmark',
        year: '1989',
    },
    {
        title: 'Sofabord',
        price: 2999,
        stock: 1,
        category: 'Stue',
        id: 12,
        parentId: 1,
        subCategory: 'Sofabord',
        img: '',
        description: 'Veldig pent brukt. Stått på et gjesterom.',
        measures: 'Lengde 110cm. Bredde 70cm. Høyde 40cm',
        color: ['Red', 'blue', 'green'],
        country: '',
        year: '',
    },
    {
        title: 'Støvletter',
        price: 1999,
        stock: 1,
        category: 'Sko',
        id: 81,
        parentId: 8,
        subCategory: 'Støvletter',
        img: '',
        description: 'brukt et par ganger',
        measures: 'Lengde 2cm. Bredde 3cm.',
        color: ['white', 'grey', 'purple'],
        country: 'Polen',
        year: '1990',
    },
    {
        title: 'Whiskeysett Globus',
        price: 4999,
        stock: 2,
        category: 'Lesesal',
        id: 91,
        parentId: 9,
        subCategory: '',
        img: 'TempBilder/2Spiserom/5Pyntegjenstander/vintagekaraffel.jpeg',
        description: 'Hele verden rundt siden 1980',
        measures: 'Høyde: 50cm ',
        color: ['black', 'brown', 'tan'],
        country: 'Skottland',
        year: '1980',
    },
    {
        title: 'Unikt Mosaikk Sofabord',
        price: 6999,
        stock: 2,
        category: 'Stue',
        id: 12,
        parentId: 1,
        subCategory: 'Sofabord',
        img: 'TempBilder/1Stue/2Sofabord/vintagemosaikkbord.jpeg',
        description: 'Unikt sofabord med unik topp.',
        measures: 'Høyde: 50cm ',
        color: ['Svart', 'Smijern'],
        country: 'Rwanda',
        year: '1970',
    },
    {
        title: 'Rundt sofabord',
        price: 4499,
        stock: 2,
        category: 'Stue',
        id: 12,
        parentId: 1,
        subCategory: 'Sofabord',
        img: 'TempBilder/1Stue/2Sofabord/loungebordvintage.jpeg',
        description: 'Rundt lite sofabord med solide bein i en fin fasong.',
        measures: 'Høyde: 34cm. Bredde: 50cm. Lengde: 50cm. ',
        color: ['Grå', 'Brun'],
        country: 'Island',
        year: '1985',
    },
    {
        title: 'Sjeselong (Skinn)',
        price: 6799,
        stock: 2,
        category: 'Stue',
        id: 14,
        parentId: 1,
        subCategory: 'Sjeselong',
        img: 'TempBilder/1Stue/3Sjeselong/vintagesjesbrownleather.jpeg',
        description: 'Fin sjeselong i skinn, lett å holde pen. Fint brukt, men veldig lite brukt.',
        measures: 'Høyde: 90cm. Bredde: 50cm. Lengde: 120cm.',
        color: ['Brun', 'Skinn'],
        country: 'Skottland',
        year: '1990',
    },
    {
        title: 'Mønstrete Sjeselong',
        price: 4599,
        stock: 2,
        category: 'Stue',
        id: 14,
        parentId: 1,
        subCategory: 'Sjeselong',
        img: 'TempBilder/1Stue/3Sjeselong/sjespattern.jpeg',
        description: 'Mønstrete sjeselong, stått på gjesterom.',
        measures: 'Høyde: 34cm. Lengde: 110cm. Bredde: 45cm.',
        color: ['Blå', 'Mønstrete'],
        country: 'England',
        year: '1983',
    },
    {
        title: 'Rød Eldre Sjeselong',
        price: 2499,
        stock: 3,
        category: 'Stue',
        id: 14,
        parentId: 1,
        subCategory: 'Sjeselong',
        img: 'TempBilder/1Stue/3Sjeselong/sjesredold.jpeg',
        description: 'Rød, skikkelig retro sjeselong. Stått på et kontor, så omtrent ikke brukt. Veldig pen stand.',
        measures: 'Høyde: 80. Lengde: 120cm. Bredde: 75cm.',
        color: ['Rød'],
        country: 'Sverige',
        year: '1984',
    },
    {
        title: 'Kommode',
        price: 5499,
        stock: 2,
        category: 'Stue',
        id: 15,
        parentId: 1,
        subCategory: 'Kommoder',
        img: '',
        description: 'Fin kommode i god stand. Stått pent oppbevart.',
        measures: 'Høyde: 80cm. Lengde: 110cm. Dybde: 40cm. ',
        color: ['Treverk'],
        country: 'Finland',
        year: '1990',
    },
    {
        title: 'Kommode (9 Skuffer)',
        price: 5899,
        stock: 2,
        category: 'Stue',
        id: 43,
        parentId: 4,
        subCategory: 'Kommoder',
        img: 'TempBilder/1Stue/4Kommoder/vintagekommodeskuffer.webp',
        description: 'Røff kommode med god plass til oppnbevaring. 9 fine skuffer. Pen stand.',
        measures: 'Høyde: 100cm. Lengde: 110cm. Dybde: 45cm. ',
        color: ['Svart'],
        country: 'Italia',
        year: '1998',
    },
    {
        title: 'Retro Kommode (8 Skuffer)',
        price: 3499,
        stock: 2,
        category: 'Stue',
        id: 43,
        parentId: 4,
        subCategory: 'Kommoder',
        img: 'TempBilder/1Stue/4Kommoder/whitesjenk.jpeg',
        description: 'Fin retro kommode. Passer for eksempel fint på soverommet.',
        measures: 'Høyde: 90cm. Lengde: 110cm. Dybde: 60cm. ',
        color: ['Hvit'],
        country: 'Denmark',
        year: '1982',
    }
];


