model.products = [
    
    // Stue
    {
        title: 'Sofa',
        price: 6999,
        stock: 1,
        category: 'Stue',
        id: 111,
        parentId: 11,
        subCategory: 'Sofa',
        img: 'TempBilder/1Stue/1Sofa/vintagesofaoker.jpeg',
        description: 'Pent brukt, men fortsatt en flott sofa. Stått lagret i bod siden 2005.',
        measures: 'Høyde: 80cm. Dybde: 50cm. Lengde: 170cm',
        color: ['Oker Gul'],
        country: 'Danmark',
        year: "1978",
    },
    {
        title: 'Spisestuestol',
        price: 1999,
        stock: 2,
        category: 'Spiserom',
        id: 112,
        parentId: 11,
        subCategory: 'Spisestuestol',
        img: 'TempBilder/2Spiserom/1stoler/habdulstol.png',
        description: 'Godt brukt stol, men fortsatt flott å se på.',
        measures: 'Høyde: 80cm. Dybde: 40cm. Lengde: 40cm',
        color: ['Brun'],
        country: 'Tyskland',
        year: "1967",
    },
    {
        title: 'Kjøkkenbord',
        price: 8999,
        stock: 2,
        category: 'Kjøkken',
        id: 113,
        parentId: 11,
        subCategory: 'Kjøkkenbord',
        img: 'TempBilder/1 Kjøkkenbord/vintagekjokkenbord.jpeg',
        description: '.',
        measures: 'Høyde: 80cm. Dybde: 50cm. Lengde: 170cm',
        color: ['Oker Gul'],
        country: 'Danmark',
        year: "2006",
    },
    {
        title: 'Unikt barbord',
        price: 6799,
        stock: 4,
        category: 'Lesesal',
        id: 122,
        parentId: 22,
        subCategory: 'Bord',
        img: 'TempBilder/3Kjøkken/Tempkitchentable/8729f31b63ae4f033a520009b94acd6048-removebg-preview.png',
        description: 'Bardisk med plass til både flasker og glass, også med kjøleboks. Stamme i svart metall med fine kontraster til den gyldne fargen. Topplate av mangotre.',
        measures: 'Høyde 100cm. Dybde 45cm. Lengde 110cm.',
        color: ['Eik', ' Sort'],
        country: 'Sverige',
        year: '1961',
    },
    // Spiserom
    {
        title: 'Seng',
        price: 8499,
        stock: 5,
        category: 'Soverom',
        id: 131,
        parentId: 31,
        subCategory: 'Seng',
        img: 'TempBilder/4 Soverom/1 Seng/vintageseng2.jpeg',
        description: 'Flott, unik seng.',
        color: ['gold', 'gylden'],
        country: 'Canada',
        year: '1968',
    },

    // Kjøkken

    {
        title: 'Sofabord',
        price: 8888,
        stock: 12,
        category: 'Stue',
        id: 142,
        parentId: 41,
        subCategory: 'Sofabord',
        img: 'TempBilder/1Stue/2Sofabord/80svintagebord.jpeg',
        description: 'To små, enkle sofabord, i fin stand.',
        measures: 'Høyde 40cm. Dybde 50cm. Høyde 30cm. Dybde 30cm.',
        color: ['Treverk'],
        country: 'Danmark',
        year: '1971',
    },
    {
        title: 'Kommode',
        price: 2499,
        stock: 1,
        category: 'Soverom',
        id: 151,
        parentId: 51,
        subCategory: 'Kommode',
        img: 'TempBilder/1Stue/4Kommoder/kommodevin.jpeg',
        description: 'Fin kommode i god stand. Fin å ha på soverommet.',
        measures: 'Høyde 80cm. Dybde 50cm.',
        color: ['Treverk'],
        country: 'Finland',
        year: '1971',
    },
    {
        title: 'Skjenk ',
        price: 3299,
        stock: 2,
        category: 'Spiserom',
        id: 162,
        parentId: 62,
        subCategory: 'Skjenk',
        img: 'TempBilder/1Stue/4Kommoder/retroskjenk.jpeg',
        description: 'Godt brukt, men i god stand. Passer fint i spiserommet.',
        measures: 'Høyde 85cm. Dybde 45cm. Bredde 100cm',
        color: ['Treverk'],
        country: 'Danmark',
        year: '1989',
    },
    {
        title: 'Sofabord',
        price: 2999,
        stock: 1,
        category: 'Stue',
        id: 171,
        parentId: 71,
        subCategory: 'Sofabord',
        img: 'TempBilder/1Stue/2Sofabord/vintagemosaikkbord.jpeg',
        description: 'Veldig pent brukt. Stått på et gjesterom.',
        measures: 'Lengde 110cm. Bredde 70cm. Høyde 40cm',
        color: ['Red', 'blue', 'green'],
        country: 'uganda',
        year: '1500~',
    },
    {
        title: 'Midlertidlig-Produkt 8',
        price: 12500,
        stock: 1,
        category: 'Sko',
        id: 181,
        parentId: 81,
        subCategory: 'Støvletter',
        img: 'TempBilder/1Stue/3Sjeselong/vintagesjesbrownleather.jpeg',
        description: 'brukt et par ganger',
        measures: 'Lengde 2cm. Bredde 3cm.',
        color: ['white', 'grey', 'purple'],
        country: 'Denmark',
        year: '1990~',
    },
    {
        title: ' Midlertidlig-Produkt 9',
        price: 4999,
        stock: 2,
        category: 'Lesesal',
        id: 191,
        parentId: 91,
        subCategory: '',
        img: 'TempBilder/2Spiserom/5Pyntegjenstander/vintagekaraffel.jpeg',
        description: 'Hele verden rundt siden 1880',
        measures: 'Høyde: 50cm ',
        color: ['black', 'brown', 'tan'],
        country: 'Denmark',
        year: '1880ca',
    },
    {
        title: 'Sofabord 2',
        price: 9999,
        stock: 2,
        category: 'Stue',
        id: 191,
        parentId: 91,
        subCategory: 'Sofabord',
        img: 'TempBilder/1Stue/2Sofabord/vintagemosaikkbord.jpeg',
        description: 'nydelig sofabord fra en eller annen kul plass',
        measures: 'Høyde: 50cm ',
        color: ['black', 'brown', 'tan'],
        country: 'Denmark',
        year: '1880ca',
    },
    {
        title: 'Sofabord 1',
        price: 4999,
        stock: 2,
        category: 'Stue',
        id: 191,
        parentId: 91,
        subCategory: 'Sofabord',
        img: 'TempBilder/1Stue/2Sofabord/loungebordvintage.jpeg',
        description: 'et lite bord, med fire bein.',
        measures: 'Høyde: 34cm ',
        color: ['black', 'brown', 'tan'],
        country: 'Denmark',
        year: '1996ca',
    },
    {
        title: 'Sjelong 1',
        price: 8999,
        stock: 3,
        category: 'Stue',
        id: 191,
        parentId: 91,
        subCategory: 'Sjeselong',
        img: 'TempBilder/1Stue/3Sjeselong/vintagesjesbrownleather.jpeg',
        description: 'et lite bord, med fire bein.',
        measures: 'Høyde: 34cm ',
        color: ['black', 'brown', 'tan'],
        country: 'Denmark',
        year: '1996ca',
    },
    {
        title: 'Sjelong 2',
        price: 8999,
        stock: 2,
        category: 'Stue',
        id: 191,
        parentId: 91,
        subCategory: 'Sjeselong',
        img: 'TempBilder/1Stue/3Sjeselong/sjespattern.jpeg',
        description: 'et lite bord, med fire bein.',
        measures: 'Høyde: 34cm ',
        color: ['black', 'brown', 'tan'],
        country: 'Denmark',
        year: '1996ca',
    },
    {
        title: 'Sjelong 3',
        price: 2999,
        stock: 7,
        category: 'Stue',
        id: 191,
        parentId: 91,
        subCategory: 'Sjeselong',
        img: 'TempBilder/1Stue/3Sjeselong/sjesredold.jpeg',
        description: 'et lite bord, med fire bein.',
        measures: 'Høyde: 34cm ',
        color: ['black', 'brown', 'tan'],
        country: 'Denmark',
        year: '1996ca',
    },
    {
        title: 'Kommoder 1',
        price: 6999,
        stock: 7,
        category: 'Stue',
        id: 191,
        parentId: 91,
        subCategory: 'Kommoder',
        img: 'TempBilder/1Stue/4Kommoder/retroskjenk.jpeg',
        description: 'et lite bord, med fire bein.',
        measures: 'Høyde: 34cm ',
        color: ['black', 'brown', 'tan'],
        country: 'Denmark',
        year: '1996ca',
    },
    {
        title: 'Kommoder 2',
        price: 5599,
        stock: 7,
        category: 'Stue',
        id: 191,
        parentId: 91,
        subCategory: 'Kommoder',
        img: 'TempBilder/1Stue/4Kommoder/vintagekommodeskuffer.webp',
        description: 'et lite bord, med fire bein.',
        measures: 'Høyde: 34cm ',
        color: ['black', 'brown', 'tan'],
        country: 'Denmark',
        year: '1996ca',
    },
    {
        title: 'Kommoder 3',
        price: 8999,
        stock: 7,
        category: 'Stue',
        id: 191,
        parentId: 91,
        subCategory: 'Kommoder',
        img: 'TempBilder/1Stue/4Kommoder/whitesjenk.jpeg',
        description: 'et lite bord, med fire bein.',
        measures: 'Høyde: 34cm ',
        color: ['black', 'brown', 'tan'],
        country: 'Denmark',
        year: '1996ca',
    },
];

